### ISSUE TITLE
Connection demo app: Blocking network modal

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-app-demo#12]
Appears when a user initiates an on-chain action (like transaction) and is currently on the wrong network. Will auto-close when the network is correct. Should appear prior to a Connection Modal if on wrong network. Should resume the user-initiated action (like connect or transact).

- [x] Modal
- [x] Check network logic
- [x] Appears when on-chain action is invoked

**Comment by MikeLockz** [comment]
![image](https://user-images.githubusercontent.com/797290/54656631-fa31fb80-4a8b-11e9-92e3-b8f3ecfbebc6.png)

**Comment by ryancreatescopy** [comment]
Doesn't pass QA: doesn't resume the user-initiated action. Also the passive banner should probably disappear when the blocking modal is triggered as it seems a bit angry at the moment!
