### ISSUE TITLE
Connection demo app: Connection modal from on-chain action

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-app-demo#16]
Variation for the connection modal displaying different content, which is triggered when a user initiates an on-chain action. Connect with MetaMask button is primary action. Modal can be cancelled/closed. Should include current network indicator. Might not make through testing.

- [x] Appears when user initiates on-chain action and is NOT already connected and verified
- [x] Connect with Metamask button
- [x] Network indicator
- [x] Modal can be closed

**Comment by MikeLockz** [comment]
![image](https://user-images.githubusercontent.com/797290/54656797-b55a9480-4a8c-11e9-9fd0-1be2ee67b928.png)

**Comment by ryancreatescopy** [comment]
Not a massive deal, but if connection flow goes straight to "Verify your account" it appears to load the connection request screens first which makes me feel like something has gone wrong in the background. Is it possible to just bypass the connection screens entirely so the first thing that loads is the verify screen in this instance?

**Comment by MikeLockz** [comment]
@ryancreatescopy - I'm not sure clear on how to reproduce on my end. Are you saying that when a user clicks on the Connect button, it should first determine if they have already connected? If they have already connected before, skip the "Connection Modal" and go to the "Verify Pending Modal"?
