### ISSUE TITLE
Connection demo app: Connection pending modal

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-app-demo#17]
Appears after user clicks the “Connect with MetaMask” button from the Connection Modal.  Prompts MetaMask with Connect prompt.

- [x] Modal with network indicator
- [x] Modal can be cancelled/closed
- [x] Modal is closed when use Connects via MetaMask

**Comment by MikeLockz** [comment]
![image](https://user-images.githubusercontent.com/797290/54656880-010d3e00-4a8d-11e9-989f-47328e779ba4.png)

**Comment by MikeLockz** [comment]
Ryan said
In most other places I've looked, the behaviour is similar. The modal either: closes, but breaks the connection process; doesn't have a close option; or the MM connection request appears without a modal. cc Caroline Ford
6 DAYS AGO
Ryan said
Ok, so current behaviour in Bounties:

If you cancel this modal, the connection request remains in MetaMask and your MM icon changes to show you have 1 outstanding action. 

However if you click on the MM icon and hit "Connect" it seemed to not work and you have to start over. (This would be awesome if it would just pick up where you left off, i.e. ask you to verify your account)

In the verification step, Bounties currently don't provide you a way to cancel that modal. You are basically trapped until you sign or don't sign the message.
6 DAYS AGO
Zach Kalman said delete
Mike Lockwitz Ryan Caroline Ford This says you can close this modal. What would happen to the connection request in MM if someone did that?

**Comment by ryancreatescopy** [comment]
Didn't pass QA: can't close the modal. I think we need to discuss whether you should be able to based on above comments.
