### ISSUE TITLE
Connection demo app: Connection cancelled during verification

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-app-demo#20]
Appears when a user rejects the signed personal message. Return user to Verify Your Account Modal as primary action.

- [x] Appears if the user clicks “Cancel” from a Sign Message prompt
- [x] Can be cancelled/closed
- [x] Secondary action "Browse as Guest" which is the same as close
- [x]  Primary action "Send Request Again"  re-triggers the MetaMask Connect prompt
- [x] The background modal should change to the Connection Pending Modal when "Send Verify Request Again" is clicked.

**Comment by MikeLockz** [comment]
![image](https://user-images.githubusercontent.com/797290/54657025-8264d080-4a8d-11e9-80da-a5de64f7e8d6.png)

**Comment by ryancreatescopy** [comment]
Didn't pass QA: "Browse as guest" should close all windows, essentially cancelling connection. At the moment the screen for the step you were on persists (e.g. verification pending screen) which the user has to close manually.
