### ISSUE TITLE
Connection demo app: Low funds modal

### ISSUE THREAD

**Issue by MikeLockz** [ConsenSys/rimble-app-demo#21]
When a user initiates an on-chain action, or continued from a Connect Button action. Shows user public address. Show QR code action button. Continue button to close the modal. Can be cancelled/closed. Show the current network status.

- [x] Appears when user initiates on-chain action and has low balance
- [x] Check wallet balance
- [x] PublicAddress with 'copy' button
- [x] QR code icon button
- [x] network indicator

**Comment by MikeLockz** [comment]
![image](https://user-images.githubusercontent.com/797290/54657071-a2948f80-4a8d-11e9-9cf5-1685c4b737ce.png)

**Comment by ryancreatescopy** [comment]
Doesn't pass QA: When I hit "Show QR code" the modal defaults to this view. So if I close and try and decrease the value of the smart contract it opens up a modal with the QR code but none of the context. There should probably be some kind of way of getting back from the QR code screen.

**Comment by MikeLockz** [comment]
Added a button to close the QR. Make sure you are connected/verified if you're using the debugger to throw the modal.

![image](https://user-images.githubusercontent.com/797290/54781320-8f92d400-4be1-11e9-887e-e49fff084f16.png)
